---
# tasks file for ansible-role-debug

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Install epdb
  pip:
    name: epdb

- shell: "ansible -m setup localhost > {{ debug_dump_file }}"
  changed_when: false
  when: "{{ debug_dump }}"
